config/routes.rb
Rails.application.routes.draw do
  root 'purchase_records#index'
  resources :products
  resources :suppliers
  resources :purchase_records do
    collection do
      get 'get_suppliers'
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :supplier_products
  has_many :purchase_records
  has_many :suppliers, through: :supplier_products

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :stock, presence: true, numericality: { greater_than_or_equal_to: 0 }

end

app/models/purchase_record.rb
class PurchaseRecord < ApplicationRecord
  belongs_to :product
  belongs_to :supplier

  validates :purchase_date, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :purchase_records
  has_many :supplier_products
  has_many :products, through: :supplier_products

  validates :name, presence: true
  validates :tel, presence: true

end

app/models/supplier_product.rb
class SupplierProduct < ApplicationRecord
  belongs_to :supplier
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @suppliers = @product.suppliers
  end

  def new
    @product = Product.new
    @suppliers = Supplier.all # 業者のリストを取得
  end

  def edit
    @product = Product.find(params[:id])
    @suppliers = Supplier.all # 業者のリストを取得
  end

  def create
    @product = Product.new(product_params)
    supplier_ids = params[:product][:supplier_ids].reject(&:empty?)
    @product.suppliers << Supplier.find(supplier_ids)
    if @product.save
      redirect_to @product, notice: '商品を登録しました。'
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    supplier_ids = params[:product][:supplier_ids].reject(&:empty?)
    @product.suppliers = Supplier.find(supplier_ids)
    if @product.update(product_params)
      redirect_to @product, notice: '商品を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.suppliers.each do |supplier|
      supplier.products.destroy(@product) # 関連する業者から商品を削除
    end
    @product.destroy # 商品を削除
    redirect_to products_url, notice: '商品を削除しました。'
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :stock)
  end
end

app/controllers/purchase_records_controller.rb
class PurchaseRecordsController < ApplicationController
  before_action :set_purchase_record, only: [:destroy, :update, :edit, :show]

  def index
    @purchase_records = PurchaseRecord.includes(:product, :supplier).all
  end

  def show
  end

  def new
    @purchase_record = PurchaseRecord.new
  end

  def edit
  end

  def create
    @purchase_record = PurchaseRecord.new(purchase_record_params)
    @product = Product.find(@purchase_record.product_id)
    @product.stock +=  @purchase_record.quantity.to_i
    if @purchase_record.save && @product.save
      redirect_to @purchase_record, notice: '作成しました。'
    else
      render :new
    end
  end

  def update
    if @purchase_record.update(purchase_record_params)
      redirect_to @purchase_record, notice: '更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @purchase_record.destroy
    redirect_to purchase_records_url, notice: '削除しました。'
  end

  def search
    product_name_match_type = params[:product_name_match_type] == 'partial' ? '%' : ''
    supplier_name_match_type = params[:supplier_name_match_type] == 'partial' ? '%' : ''
    
    conditions = []
    values = []
    if params[:purchase_date].present?
      conditions << "purchase_records.purchase_date = ?"
      values << params[:purchase_date]
    end
    
    if params[:product_name].present?
      conditions << "products.name LIKE ?"
      values << "#{product_name_match_type}#{params[:product_name]}"
    end
    
    if params[:supplier_name].present?
      conditions << "suppliers.name LIKE ?"
      values << "#{supplier_name_match_type}#{params[:supplier_name]}"
    end
    
    if params[:product_stock].present?
      conditions << "products.stock > ?"
      values << params[:product_stock]
    end
    
      @purchase_records = PurchaseRecord
      .joins("LEFT OUTER JOIN products ON purchase_records.product_id = products.id")
      .joins("LEFT OUTER JOIN suppliers ON purchase_records.supplier_id = suppliers.id")
      .select('purchase_records.*, products.name as product_name, suppliers.name as supplier_name')
      .where(conditions.join(" AND "), *values)
    
    render :index
  end

  def get_suppliers
    product = Product.find_by(id: params[:product_id])
    if product.nil?
      render json: []
    else
      @suppliers = product.suppliers.map do |supplier|
        {
          id: supplier.id,
          name: supplier.name
        }
      end
      render json: @suppliers
    end
  end

  private
    def set_purchase_record
      @purchase_record = PurchaseRecord.includes(:product, :supplier).find(params[:id])
    end

    def purchase_record_params
      params.require(:purchase_record).permit(:purchase_date, :quantity, :product_id, :supplier_id)
    end
end
##sourcetreeテスト用２

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController

  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
    @products = @supplier.products
    end

  def new
    @supplier = Supplier.new
    @products = Product.all # 商品のリストを取得
  end

  def edit
    @supplier = Supplier.find(params[:id])
    @products = Product.all # 商品のリストを取得
  end

  def create
    @supplier = Supplier.new(supplier_params)
    product_ids = params[:supplier][:product_ids].reject(&:empty?)
    @supplier.products << Product.find(product_ids)
    if @supplier.save
      redirect_to @supplier, notice: '業者を登録しました。'
    else
      render :new
    end
  end

  def update
    @supplier = Supplier.find(params[:id])
    product_ids = params[:supplier][:product_ids].reject(&:empty?)
    @supplier.products = Product.find(product_ids)
    if @supplier.update(supplier_params)
      redirect_to @supplier, notice: '業者を更新しました。'
    else
      render :edit
    end
  end
  def destroy
    @supplier = Supplier.find(params[:id])
    @supplier.products.each do |product|
      product.suppliers.destroy(@supplier) # 関連する商品から業者を削除
    end
    @supplier.destroy # 業者を削除
    redirect_to suppliers_url, notice: '業者を削除しました。'
  end

  private
  def supplier_params
    params.require(:supplier).permit(:name, :tel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchase_records_helper.rb
module PurchaseRecordsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <!-- ナビゲーションバーを追加 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Stockin', purchase_records_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "新規仕入登録", new_purchase_record_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "商品一覧", products_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "業者一覧", suppliers_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1 class="mb-4">商品編集</h1>

<%= form_with(model: @product, local: true, class: 'mt-4') do |form| %>
  <div class="mb-3">
    <%= form.label :name, '商品名', class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :price, '単価', class: 'form-label' %>
    <div class="input-group">
      <%= form.number_field :price, class: 'form-control' %>
      <span class="input-group-text">円</span>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :stock, '在庫数', class: 'form-label' %>
    <div class="input-group">
      <%= form.number_field :stock, class: 'form-control' %>
      <span class="input-group-text">個</span>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :supplier_ids, '取扱業者', class: 'form-label' %>
    <%= form.collection_select :supplier_ids, @suppliers, :id, :name, {selected: @product.supplier_ids}, {multiple: true, class: 'form-control'} %>
  </div>

  <%= form.submit '商品更新', class: 'btn btn-primary' %>
  <%= link_to '戻る', products_path, class: 'btn btn-secondary', style: 'margin-left: 10px' %>
<% end %>

app/views/products/index.html.erb
<div class="d-flex justify-content-between mb-4">
  <h1 class="h3">商品一覧</h1>
  <%= link_to '新規商品登録', new_product_path, class: 'btn btn-primary' %>
</div>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>商品名</th>
        <th>単価</th>
        <th>在庫数</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product.name, product_path(product), class: 'text-decoration-none' %></td>
          <td><%= product.price.to_i.to_s(:delimited, delimiter: ',') %>円</td>
          <td><%= product.stock.to_i.to_s(:delimited, delimiter: ',') %>個</td>
          <td><%= link_to '編集', edit_product_path(product), class: 'btn btn-outline-primary btn-sm' %></td>
          <td><%= link_to '削除', product_path(product), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-outline-danger btn-sm' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<h1 class="mb-4">商品登録</h1>

<%= form_for(@product, class: "mt-4") do |f| %>
  <div class="mb-3">
    <%= f.label :name, "商品名", class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :price, "単価", class: "form-label" %>
    <div class="input-group">
      <%= f.number_field :price, class: "form-control" %>
      <span class="input-group-text">円</span>
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :stock, "在庫数", class: "form-label" %>
    <div class="input-group">
      <%= f.number_field :stock, class: "form-control" %>
      <span class="input-group-text">個</span>
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :supplier_ids, "取扱業者", class: "form-label" %>
    <%= f.collection_select :supplier_ids, @suppliers, :id, :name, {}, { multiple: true, class: "form-control" } %>
  </div>

  <%= f.submit "作成", class: "btn btn-primary" %>
  <%= link_to "戻る", products_path, class: "btn btn-secondary", style: 'margin-left: 10px' %>
<% end %>

app/views/products/show.html.erb
<h1 class="mb-4">商品詳細</h1>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">商品名</h5>
    <p class="card-text"><%= @product.name %></p>
  </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">単価</h5>
    <p class="card-text"><%= number_to_currency(@product.price, unit: '') %>円</p>
  </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">在庫数</h5>
    <p class="card-text"><%= @product.stock.to_i.to_s(:delimited, delimiter: ',') %>個</p>
  </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">取扱業者</h5>
    <% @product.suppliers.each do |supplier| %>
      <%= link_to supplier.name, supplier_path(supplier), class:"btn btn-outline-primary" %>
    <% end %>
  </div>
</div>

<%= link_to '編集', edit_product_path(@product), class: 'btn btn-primary' %>
<%= link_to '削除', product_path(@product), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger', style: 'margin-left: 10px' %>
<%= link_to "戻る", products_path, class: "btn btn-secondary", style: 'margin-left: 10px' %>

app/views/purchase_records/edit.html.erb
<%= javascript_pack_tag 'get_suppliers' %>

<div class="container">
  <h1 class="mb-4">仕入編集</h1>
  <%= form_with(model: @purchase_record, local: true, class: 'mt-4') do |form| %>
    <% if @purchase_record.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(@purchase_record.errors.count, "error") %> prohibited this purchase record from being saved:</h2>
        <ul>
          <% @purchase_record.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :purchase_date, '仕入日', class: 'form-label' %>
      <%= form.date_field :purchase_date, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :quantity, '仕入数', class: 'form-label' %>
      <div class="input-group">
        <%= form.number_field :quantity, class: 'form-control' %>
        <span class="input-group-text">個</span>
      </div>
    </div>

    <div class="mb-3">
      <%= form.label :product_id, '商品名', class: 'form-label' %>
      <%= form.collection_select :product_id, Product.all, :id, :name, { selected: @purchase_record.product_id }, { class: 'form-select' } %>
    </div>

    <div class="mb-3">
      <%= form.label :supplier_id, '業者名', class: 'form-label' %>
      <%= form.collection_select :supplier_id, Supplier.all, :id, :name, { selected: @purchase_record.supplier_id }, { class: 'form-select' } %>
    </div>

      <%= form.submit '仕入更新', class: 'btn btn-primary', data: { confirm: "商品の在庫数は変更されません。&#13;&#10;更新しますか？".html_safe } %>
      <%= link_to '戻る', purchase_records_path, class: 'btn btn-secondary', style: 'margin-left: 10px' %>
  <% end %>
</div>

app/views/purchase_records/index.html.erb
<div class="d-flex justify-content-between mb-4">
  <h1 class="h3">仕入一覧</h1>
  <%= link_to '新規仕入登録', new_purchase_record_path, class: 'btn btn-primary' %>
</div>

<div class="card mb-2">
  <div class="card-body">
    <%= form_tag search_purchase_records_path, method: :get, class: 'mb-4' do %>
      <div class="row g-3">
        <div class="col-md-3 mb-1">
          <%= label_tag :purchase_date, "日付", class: 'form-label' %>
          <%= date_field_tag :purchase_date, params[:purchase_date], class: 'form-control' %>
        </div>

        <div class="col-md-3 mb-1">
          <%= label_tag :product_name, "商品名", class: 'form-label' %>
          <%= text_field_tag :product_name, params[:product_name], class: 'form-control' %>
          <div class="d-flex justify-content-start">
            <div class="form-check">
              <%= radio_button_tag :product_name_match_type, "forward", true, class: 'form-check-input' %>
              <%= label_tag :product_name_match_type_forward, "前方一致", class: 'form-check-label' %>
            </div>
            <div class="px-3"></div>
            <div class="form-check">
              <%= radio_button_tag :product_name_match_type, "partial", false, class: 'form-check-input' %>
              <%= label_tag :product_name_match_type_partial, "部分一致", class: 'form-check-label' %>
            </div>
          </div>
        </div>

        <div class="col-md-3 mb-1">
          <%= label_tag :supplier_name, "業者名", class: 'form-label' %>
          <%= text_field_tag :supplier_name, params[:supplier_name], class: 'form-control' %>
          <div class="d-flex justify-content-start">
            <div class="form-check">
              <%= radio_button_tag :supplier_name_match_type, "forward", true, class: 'form-check-input' %>
              <%= label_tag :supplier_name_match_type_forward, "前方一致", class: 'form-check-label' %>
            </div>
            <div class="px-3"></div>
            <div class="form-check">
              <%= radio_button_tag :supplier_name_match_type, "partial", false, class: 'form-check-input' %>
              <%= label_tag :supplier_name_match_type_partial, "部分一致", class: 'form-check-label' %>
            </div>
          </div>
        </div>

        <div class="col-md-3 mb-1">
          <%= label_tag :product_stock, "在庫数", class: 'form-label' %>
          <div class="input-group">
            <%= number_field_tag :product_stock, params[:product_stock], class: 'form-control' %>
            <span class="input-group-text">個より多い</span>
          </div>
        </div>

      </div>
    <%= submit_tag "検索", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>仕入日</th>
        <th>商品名</th>
        <th>仕入数</th>
        <th>業者名</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @purchase_records.each do |purchase_record| %>
        <tr>
          <td><%= link_to purchase_record.purchase_date, purchase_record_path(purchase_record), class: 'text-decoration-none' %></td>
          <td><%= link_to (purchase_record.product.present? ? purchase_record.product.name : "(削除済)"), purchase_record.product.present? ? product_path(purchase_record.product) : "#", class: 'text-decoration-none' %></td>
          <td><%= purchase_record.quantity.to_i.to_s(:delimited, delimiter: ',') %></td>
          <td><%= link_to (purchase_record.supplier.present? ? purchase_record.supplier.name : "(削除済)"), purchase_record.supplier.present? ? supplier_path(purchase_record.supplier) : "#", class: 'text-decoration-none' %></td>
          <td><%= link_to '編集', edit_purchase_record_path(purchase_record), class: 'btn btn-outline-primary btn-sm' %></td>
          <td><%= link_to '削除', purchase_record_path(purchase_record), method: :delete, data: { confirm: "商品の在庫数は変更されません。&#13;&#10;削除しますか？".html_safe }, class: 'btn btn-outline-danger btn-sm' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/purchase_records/new.html.erb
<%= javascript_pack_tag 'get_suppliers' %>
<h1>仕入登録</h1>
<%= form_with(model: @purchase_record, local: true) do |form| %>
  <% if @purchase_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase_record.errors.count, "error") %> prohibited this purchase record from being saved:</h2>

      <ul>
      <% @purchase_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :purchase_date, "仕入日", class: "form-label" %>
    <%= form.date_field :purchase_date, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :quantity, '仕入数', class: "form-label" %>
      <div class="input-group">
        <%= form.number_field :quantity, class: 'form-control' %>
        <span class="input-group-text">個</span>
      </div>
  </div>

  <div class="mb-3">
    <%= form.label :product_id, "商品名", class: "form-label" %>
    <%= form.collection_select :product_id, Product.all, :id, :name, {}, class: 'form-select' %>
  </div>

  <div class="mb-3">
    <%= form.label :supplier_id, "業者名", class: "form-label" %>
    <%= form.collection_select :supplier_id, [], :id, :name, {}, class: 'form-select' %>
  </div>

    <%= form.submit '仕入登録', class: 'btn btn-primary' %>
    <%= link_to '戻る', purchase_records_path, class: 'btn btn-secondary', style: 'margin-left: 10px' %>
<% end %>

app/views/purchase_records/show.html.erb
<h1 class="mb-4">仕入詳細</h1>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">仕入日</h5>
    <p class="card-text"><%= @purchase_record.purchase_date %></p>
  </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">個数</h5>
    <p class="card-text"><%= @purchase_record.quantity.to_i.to_s(:delimited, delimiter: ',') %></p>
  </div>
</div>

<div class="card mb-3"">
  <div class="card-body">
    <h5 class="card-title">商品名</h5>
    <% unless @purchase_record.product == nil %>
      <%= link_to @purchase_record.product.name, product_path(@purchase_record.product), class:"btn btn-outline-primary" %>
    <% end %>
  </div>
</div>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">業者名</h5>
    <% unless @purchase_record.supplier == nil%>
      <%= link_to @purchase_record.supplier.name, supplier_path(@purchase_record.supplier), class:"btn btn-outline-primary" %>
    <% end %>
  </div>
</div>

<%= link_to '編集', edit_purchase_record_path(@purchase_record), class: 'btn btn-primary' %>
<%= link_to '削除', purchase_record_path(@purchase_record), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger', style: 'margin-left: 10px' %>
<%= link_to '戻る', purchase_records_path, class: 'btn btn-secondary', style: 'margin-left: 10px' %>

app/views/suppliers/edit.html.erb
<h1 class="mb-4">業者編集</h1>

<%= form_for(@supplier, class: 'mt-4') do |f| %>
  <div class="mb-3">
    <%= f.label :name, '業者名', class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :tel, '電話番号', class: 'form-label' %>
    <%= f.text_field :tel, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :product_ids, '取扱商品', class: 'form-label' %>
    <%= f.collection_select :product_ids, @products, :id, :name, {selected: @supplier.product_ids}, {multiple: true, class: 'form-control'} %>
  </div>

  <%= f.submit '業者更新', class: 'btn btn-primary' %>
  <%= link_to '戻る', suppliers_path, class: 'btn btn-secondary', style: 'margin-left: 10px' %>
<% end %>

app/views/suppliers/index.html.erb
<div class="d-flex justify-content-between mb-4">
  <h1 class="h3">業者一覧</h1>
  <%= link_to '新規業者登録', new_supplier_path, class: 'btn btn-primary' %>
</div>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>業者名</th>
        <th>電話番号</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= link_to supplier.name, supplier_path(supplier), class: 'text-decoration-none' %></td>
          <td><%= supplier.tel %></td>
          <td><%= link_to '編集', edit_supplier_path(supplier), class: 'btn btn-outline-primary btn-sm' %></td>
          <td><%= link_to '削除', supplier_path(supplier), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-outline-danger btn-sm' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/suppliers/new.html.erb
<h1 class="mb-4">業者登録</h1>

<%= form_for(@supplier, class: 'mt-4') do |f| %>
  <div class="mb-3">
    <%= f.label :name, '業者名', class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :tel, '電話番号', class: 'form-label' %>
    <%= f.text_field :tel, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :product_ids, '取扱商品', class: 'form-label' %>
    <%= f.collection_select :product_ids, @products, :id, :name, {}, { multiple: true, class: 'form-control' } %>
  </div>

  <%= f.submit '作成', class: 'btn btn-primary' %>
  <%= link_to '戻る', suppliers_path, class: 'btn btn-secondary', style: 'margin-left: 10px' %>
<% end %>

app/views/suppliers/show.html.erb
<h1 class="mb-4">業者詳細</h1>

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">業者名</h5>
    <p class="card-text"><%= @supplier.name %></p>
  </div>
</div>
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">電話番号</h5>
    <p class="card-text"><%= @supplier.tel %></p>
  </div>
</div>
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">取扱商品</h5>
    <% @products.each do |product| %>
      <%= link_to product.name, product_path(product), class:"btn btn-outline-primary" %>
    <% end %>
  </div>
</div>
<%= link_to '編集', edit_supplier_path(@supplier), class: 'btn btn-primary' %>
<%= link_to '削除', supplier_path(@supplier), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger', style: 'margin-left: 10px' %>
<%= link_to '戻る', suppliers_path, class: 'btn btn-secondary', style: 'margin-left: 10px' %>